spring.application.name=Postera
spring.datasource.url=${POSTERA_DB_URL}
spring.datasource.username=${POSTERA_DB_USERNAME}
spring.datasource.password=${POSTERA_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
