CREATE TABLE message_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT fk_message_images_message FOREIGN KEY (message_id) REFERENCES mail_messages (id) ON DELETE CASCADE
);
