CREATE TABLE timeline_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_timeline_posts_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);

CREATE TABLE timeline_post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    display_order INTEGER NOT NULL,
    CONSTRAINT fk_timeline_post_images_post FOREIGN KEY (post_id) REFERENCES timeline_posts (id) ON DELETE CASCADE
);

CREATE INDEX idx_timeline_posts_created_at ON timeline_posts (created_at DESC);
