CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_friendships_sender FOREIGN KEY (sender_id) REFERENCES app_users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_receiver FOREIGN KEY (receiver_id) REFERENCES app_users (id) ON DELETE CASCADE,
    CONSTRAINT uq_friendships_sender_receiver UNIQUE (sender_id, receiver_id)
);

CREATE INDEX idx_friendships_sender_id ON friendships (sender_id);
CREATE INDEX idx_friendships_receiver_id ON friendships (receiver_id);
CREATE INDEX idx_friendships_status ON friendships (status);
