CREATE TABLE timeline_post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_timeline_reactions_post FOREIGN KEY (post_id) REFERENCES timeline_posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_timeline_reactions_user FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE,
    CONSTRAINT uk_timeline_reaction_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_timeline_reactions_post ON timeline_post_reactions (post_id);
