CREATE TABLE post_comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT NOT NULL,
    author_id   BIGINT NOT NULL,
    parent_id   BIGINT,
    content     TEXT   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_post_comments_post   FOREIGN KEY (post_id)   REFERENCES timeline_posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_author FOREIGN KEY (author_id) REFERENCES app_users      (id) ON DELETE CASCADE,
    CONSTRAINT fk_post_comments_parent FOREIGN KEY (parent_id) REFERENCES post_comments  (id) ON DELETE CASCADE
);

CREATE INDEX idx_post_comments_post   ON post_comments (post_id, created_at);
CREATE INDEX idx_post_comments_parent ON post_comments (parent_id);
