CREATE TABLE email_verification_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    code_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_email_verification_codes_user
        FOREIGN KEY (user_id) REFERENCES app_users (id) ON DELETE CASCADE
);
