CREATE TABLE mail_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    important BOOLEAN NOT NULL DEFAULT FALSE,
    trash BOOLEAN NOT NULL DEFAULT FALSE,
    draft BOOLEAN NOT NULL DEFAULT FALSE,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    CONSTRAINT fk_mail_messages_sender FOREIGN KEY (sender_id) REFERENCES app_users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_mail_messages_receiver FOREIGN KEY (receiver_id) REFERENCES app_users (id) ON DELETE RESTRICT
);

CREATE INDEX idx_mail_messages_receiver ON mail_messages (receiver_id, sent_at DESC);
CREATE INDEX idx_mail_messages_sender ON mail_messages (sender_id, sent_at DESC);
