CREATE TABLE mail_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    owner_id BIGINT NOT NULL,
    CONSTRAINT uq_mail_categories_owner_name UNIQUE (owner_id, name),
    CONSTRAINT fk_mail_categories_owner FOREIGN KEY (owner_id) REFERENCES app_users (id) ON DELETE CASCADE
);

ALTER TABLE mail_messages ADD COLUMN category_id BIGINT;
ALTER TABLE mail_messages ADD CONSTRAINT fk_mail_messages_category
    FOREIGN KEY (category_id) REFERENCES mail_categories (id) ON DELETE SET NULL;
