CREATE TABLE message_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    reported_by_user_id BIGINT NOT NULL,
    reported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_message_reports_message_user UNIQUE (message_id, reported_by_user_id),
    CONSTRAINT fk_message_reports_message FOREIGN KEY (message_id) REFERENCES mail_messages (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_reports_user FOREIGN KEY (reported_by_user_id) REFERENCES app_users (id) ON DELETE RESTRICT
);
