ALTER TABLE mail_messages ADD COLUMN sender_trash BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mail_messages ADD COLUMN receiver_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE mail_messages ADD COLUMN sender_deleted BOOLEAN NOT NULL DEFAULT FALSE;
